### ISSUE TITLE
Generate Irrigation Schedule

### ISSUE THREAD

**Issue by iliasmachairas** [aquacropos/aquacrop#129]
Hello, 

First of all, thank you for writing this awesome package. 

I would like to write some code so that AquaCrop-OSPy can suggest the irrigation schedule. I followed this tutorial regarding the Aqua Crop GUI. (https://www.youtube.com/watch?v=o5P35ogKDvw&ab_channel=FoodandAgricultureOrganizationoftheUnitedNations)
I have also studied the 4 notebooks you have attached on the documentation. I would like to to know when irrigation needs to take place. I would also like to use different water depths (in mm) over the growing season as it is shown on the video. For instance, after the 1st of May, 30mm and after the 1st of August, 50mm using a different RAW or soil moisture target. 

Based on the documentation and some jupyter notebooks, I selected rrMethod=1 as the closets option to what I want to do. Irrigation is triggered if soil water content drops below a specified threshold (or four thresholds representing four major crop growth stages (emergence, canopy growth, max canopy, senescence). I have written the following code (code regarding importing the packages has been removed to keep the question short)

`
from aquacrop import AquaCropModel, Soil, Crop, InitialWaterContent, IrrigationManagement
from aquacrop.utils import prepare_weather, get_filepath
import numpy as np
import matplotlib.pyplot as plt
from scipy.optimize import fmin

smts = [99]*4 # soil moisture targets [99, 99, 99, 99]
max_irr_season = 300 # 300 mm (water)
path = get_filepath('champion_climate.txt')
wdf = prepare_weather(path)
year1 = 2018
year2 = 2018
maize = Crop('Maize',planting_date='05/01') # define crop
loam = Soil('ClayLoam') # define soil
init_wc = InitialWaterContent(wc_type='Pct',value=[40]) # define initial soil water conditions

irrmngt = IrrigationManagement(irrigation_method=1,SMT=smts,MaxIrrSeason=max_irr_season) # define irrigation management
model = AquaCropModel(f'{year1}/05/01',f'{year2}/10/31',wdf,loam,maize,
                      irrigation_management=irrmngt,initial_water_content=init_wc)
model.run_model(till_termination=True)`

I cannot find when and how much water (depth in mm) needs to be irrigitated. I checked model._outputs. model.irrigation_management.Schedule retrurns an array of zeros. I also tried dir(model.irrigation_management) to have a look at other methods and attributes but without any success.

Is what I am asking possible via AquaCrop-OSPy or have I misunderstood any concept?

Thanks for your time!
Kind regards,
Ilias

**Comment by Han-Su22** [comment]
Hello Ilias,

Did you have a look at model_os._outputs.water_flux['IrrDay']? This is the irrigated water for each day.

Best,
Han

**Comment by mutyalusheshu** [comment]
Yes !!

**Comment by iliasmachairas** [comment]
Thanks both of you for the quick reply!

I have checked https://aquacropos.github.io/aquacrop/solution/ but I could not find the spot where model._outputs.water_flux['IrrDay'] is explained. Is there any other documentation where the outputs of the model are explained? Could you attach a link?

Thanks in advance.  

I will close the issue afterwards.

**Comment by Han-Su22** [comment]
Hi Ilias,

Glad to know it helps. I learned it from the code, aquacrop/timestep/run_single_timestep.py, lines 469-557. These lines explain where IrrDay gets the value, and all kinds of outputs. It's also possible to generate other outputs for your own purposes if you are familiar with Python. In this case, you may also need to look at aquacrop/entities/output.py and aquacrop/timestep/outputs_when_model_is_finished.py to add your own output.

Best,
Han
