### ISSUE TITLE
irrigation.py irrigation method 1 has test code hard-code value of 15 mm

### ISSUE THREAD

**Issue by mrmayn** [aquacropos/aquacrop#132]
Hello, in irrigation.py for Irr Method 1, there is a hard-coded value put in for testing purposes that was left in. Could you update the main branch by removing the hard code and restoring the main code, `Irr = min(IrrMngt_MaxIrr, IrrReq)` ? I thought I would raise the issue here so others who use the package for the first time don't have the same issue.
![image](https://github.com/aquacropos/aquacrop/assets/108820457/99641e3e-6fff-4d42-87f7-5e54a41dd2be)

**Comment by tfoster88** [comment]
Thanks @Han-Su22 and @oleksmyialk. I've been away these past few weeks, but will look into this over coming days. Clearly an issue with irrigation test that will be an easy fix, and we will check the others raised by Oleks at same time and implement any changes needed

**Comment by tfoster88** [comment]
This has now been fixed in last release
