### ISSUE TITLE
How to export a simulation result file

### ISSUE THREAD

**Issue by 1150376430** [aquacropos/aquacrop#155]
Hello, can the simulation results of aquacrop be saved as a file? What code needs to be added?

**Comment by Han-Su22** [comment]
Hi, depending on which variables you want to have. In general, you can have

model.outputs.final_stats

to return your final results. This gives you a pandas dataframe. You can use pandas function to save the results into a csv file or others.

**Comment by 1150376430** [comment]
I am really grateful!
