### ISSUE TITLE
Aquacrop runtime error

### ISSUE THREAD

**Issue by 1150376430** [aquacropos/aquacrop#156]
Hello, I am getting the following error when running aquacrop.
Error while finding module specification for 'aquacrop.scripts.initiate_library' (ModuleNotFoundError: No module named 'aquacrop')

**Comment by tfoster88** [comment]
If you receive an error message such as "No module named aquacrop.scripts.initiate_library" or "ModuleNotFoundError: No module named 'aquacrop.solution.solution_root_zone_water'", please try the following troubleshooting steps:

1. Run "python -m aquacrop.scripts.initiate_library" in your terminal, if this generates an error such as "RuntimeError: Attempted to compile AOT function without the compiler used by numpy.distutils present. Cannot find suitable msvc.", then you need to download and install an MSVC compiler such as the one included in Visual Studio build tools (see e.g. https://www.youtube.com/watch?v=p_R3tXSq0KI).

2. If Step 1 doesn't help, then you can run aquacrop in pure python (this will be slower) using: <br>
```import os```<br>
```os.environ['DEVELOPMENT'] = 'DEVELOPMENT'```

**Comment by 1150376430** [comment]
Thank you for your response. Despite errors remaining after adopting option 2, it is surprising that operational results can still be obtained.
