### ISSUE TITLE
compiling ahead of time (remove jit)

### ISSUE THREAD

**Issue by thomasdkelly** [aquacropos/aquacrop#17]
To spead up simulations, the numba jit compiler is used throughout to speed up functions. Would prefer this was done ahead of time during the build process so users do not have to wait 60 secs every time they import aquacrop. 

Numba does now have this functionality so will have to test if it can be used https://numba.readthedocs.io/en/stable/user/pycc.html

**Comment by thomasdkelly** [comment]
I have now created a new branch "nojit" which has removed jit decorators from the code so we can explore other ways of speeding up the code. 

I have tried using numba's AOT compling modules (link above) and have has some success compiling a few of the functions in solution.py ahead of time.

As some of the functions read in jitclass objects as arguments, these cannot currently be used with AOT compilation. The jitclass object could potentially be replaced by dictionaries as i think these are compatible with jit AOT.

**Comment by arongergely** [comment]
As a quick fix we could look into compiler caching via numba? I have not pursued this yet but see: https://numba.readthedocs.io/en/stable/developer/caching.html
Or perhaps did anyone looked into this yet?

**Comment by arongergely** [comment]
Nevertheless using JIT for non-JIT of course does not seem ideal.

**Comment by thomasdkelly** [comment]
I have not looked at the cache option yet, ideally we would like to distribute the code already compiled, or potentially compile the code during the setup.py. This second option is less ideal for running in colab as you still have to compile when you pip install aquacrop, however for local use it is better than the current situation.

**Comment by rbavery** [comment]
I'm taking a stab at this (replacing jit with aot and ensuring it doesn't degrade performance). we'll see where I get with it this weekend.

**Comment by rbavery** [comment]
> As some of the functions read in jitclass objects as arguments, these cannot currently be used with AOT compilation. The jitclass object could potentially be replaced by dictionaries as i think these are compatible with numba AOT.

I'm going ahead with this approach, it doesn't look like jitclasses will be supported soon, see https://github.com/numba/numba/issues/6648

**Comment by rbavery** [comment]
Documenting the current state of the library in terms of speed:

| Task     | Speed in seconds |
| ----------- | ----------- |
| JIT Compile Time     |    66.75    |
| Tunis Run without JIT   |     39.67   |
| Tunis Run with JIT   | 3.26       |
| Tunis Run with AOT    |    ?    |

**Comment by rbavery** [comment]
@thomasdkelly I'm not sure that python dicts can be used with AOT. These are the supported types https://numba.pydata.org/numba-doc/dev/reference/types.html#numba-types and this doc indicates only these can be used in function signatures: https://numba.pydata.org/numba-doc/dev/user/pycc.html  I think with AOT we are currently limited to ints, floats, and arrays of those types. potentially, the solution is to pass around ordered arrays of parameters instead of jitclasses or dictionaries, though that's probably not super desirable because it makes the code harder to read and track during debugging.

I've created a forum post to get some tips: https://numba.discourse.group/t/whats-the-recommended-way-to-pass-around-large-amounts-of-parameters-that-works-with-aot/1154

**Comment by thomasdkelly** [comment]
Hi Ryan thanks for this info and the pull request. How did you perform the 'without jit' test run? Did you use the nojit branch of the repo?

The tests are a good idea, i think i may add another test that runs the tunis example maybe 10 times to get an average "time per 30 year simulation" metric, as this is the number we want to keep fast as we improve the import/compilation time. (this could also be "time per 1 year simulation").

I have had a good look around the links you provided and through the numba docs/source code and it may be worth (at least for the short-medium term) just trying to pass floats and arrays into the solution.py functions then compiling with numba.cc as you have done in your pull request. 

This can be done in two ways:

```
# old code with jit classess (where crop and soil are jit classes)
def func(crop,profile):
    a=0
    b=0
    for layer in profile.layers:
        a += crop.GCG *profile.dz
        b+=crop.CDC*profile.dzsum
    return a,b

answer = func(crop,profile)


# (1) new code with explicit arguments 
def func(crop_CGC,crop_CDC,profile_layers,profile_dz,profile_dzsum):
    a=0
    b=0
    for layer in profile_layers:
        a += crop_GCG *profile_dz
        b+=crop_CDC*profile_dzsum
    return a,b

answer = func(crop.CGC,crop.CDC,profile.layers,profile.dz,profile.dzsum)


# (2) new code with packaged arguments
def func(func_args,profile_layers):
    crop_CGC,crop_CDC,profile_dz,profile_dzsum=func_args
    a=0
    b=0
    for layer in profile_layers:
        a += crop_GCG *profile_dz
        b+=crop_CDC*profile_dzsum
    return a,b

func_args = np.array([crop.CGC,crop.CDC,profile.dz,profile.dzsum])
answer = func(func_args,profile.layers)

```

This isnt ideal as the code looks messy and could lead to some mistakes with so many functions arguments but it would lead to a simple AOT compilation as everything is ints, floats and arrays. If numba ever incorperates jitclassess or dicts (which isnt beyond possibility since they work with the jit compiler) we can change it back.


The other solution is to use cython which would probably be too big a headache implement at this stage when we have other features we would rather spend time on. Though it isnt something to rule out forever as it does allow you to pre compile code that includes custom classes.

**Comment by thomasdkelly** [comment]
Let me know what you think. Solution 1 is how the code used to look (before this github repo) in early development when i couldnt get jitclasses to work. Its probably a couple days work and just involves:

1. copying sections of code into a text editor
2. ctrl+H to replace `crop.` with `crop_` (and similarly for other classes)
3. adjust the function arguments
4. adjust function calls (luckily most are just called once in timestep.py)
5. add the cc.export decorator

**Comment by thomasdkelly** [comment]
#33
