### ISSUE TITLE
Crop type

### ISSUE THREAD

**Issue by Rimagination** [aquacropos/aquacrop#173]
May I ask how to customize the parameters of perennial herbaceous plants? Just like in AquaCrop v7.1 Windows version, the current AquaCrop-OSPy parameters seem to be limited to three types of annual crops.
![image](https://github.com/user-attachments/assets/161762d1-6315-4463-b591-3f746f3d01a1)

**Comment by tfoster88** [comment]
Hi @Rimagination. At the moment we haven't yet added this feature to the Python code we developed based on FAO AquaCrop. We are hoping to do this in a future release, but this will most likely be later in 2024 or early 2025 as we will need time to refine the code and properly test before releasing.

**Comment by kendonB** [comment]
@tfoster88 do you have a revised estimate of when herbaceous forage crops will be implemented?
