### ISSUE TITLE
Groundnut

### ISSUE THREAD

**Issue by prasvenk83** [aquacropos/aquacrop#178]

**Comment by prasvenk83** [comment]
Can anyone share crop parameters for the groundnut crop to be used in Aquacropos-py? Thank you.

**Comment by tfoster88** [comment]
@prasvenk83 At the moment, there is not an official groundnut parameter file for AquaCrop provided by FAO. You could check the literature to see if others have applied and tested the model for groundnut as a starting point, but we don't have a default parameter set at this point for this crop (although would definitely be interesting to look into in the future)
