### ISSUE TITLE
numpy version requirement

### ISSUE THREAD

**Issue by thomasdkelly** [aquacropos/aquacrop#24]
A recent merge changed the numpy requirement to numpy>=1.21.

As of wiriting the current version is 1.22.1 so our requirement is quite stringent. Not sure if this is completely necessary.

numpy=1.21 also requires python=3.8 so this has caused me an error when trying to run setup.py within aquacrop.

**Comment by arongergely** [comment]
When installing locally in development mode via  `pip install -e .` , it picks this up I get:
```
ERROR: numba 0.55.0 has requirement numpy<1.22,>=1.18, but you'll have numpy 1.22.1 which is incompatible.
```
The model won't run for the same reason.
For numba 0.55 the  max numpy version is 1.22.0:

https://github.com/numba/numba/blob/release0.55/setup.py#L26

There are some minimum requirements as well (numpy 1.18,  python 3.7) 

Opened PR with a fix: #34

**Comment by arongergely** [comment]
About python 3.7 being a minimum requirement, that may be a bit steep as well? Not sure if we can do anything about it, other than looking at different numba versions maybe

**Comment by thomasdkelly** [comment]
#34
