### ISSUE TITLE
update notebooks

### ISSUE THREAD

**Issue by thomasdkelly** [aquacropos/aquacrop#62]
Have just experienced an issue where google colab cannot find the latest version of aquacrop==2.1, despite everything uploading correctly. So will add an extra cell to the notebooks that allows people to install direct from github 
`!pip install git+https://github.com/aquacropos/aquacrop`

Also will add a cell that allows people to run in pure python rather than have to compile the modules.
```
import os
os.environ['DEVELOPMENT'] = 'True'
```
 Im not sure how many people will find it useful but is worth adding in.

**Comment by Bowhaven** [comment]
Implemented both these changes as specified.
