### ISSUE TITLE
forum down

### ISSUE THREAD

**Issue by thomasdkelly** [aquacropos/aquacrop#67]
The forum went down a yesterday so am using this as an excuse to pivot away from having a seperate forum and just keeping all discussion on this github repo. PLease direct all comments and discussion to the Discussions section above, or by creating issues and PRs

**Comment by charalamm** [comment]
That is perfect. It wouldbe useful if someone transfered the answears of github issues like [this](https://github.com/aquacropos/aquacrop/issues/20) from thr forum to the related github issue as a comment. I would do it but the forum  currenlty down. I will try to keep an eye and do it when it is back up
