### ISSUE TITLE
FutureWarning regarding Pandas loc/iloc in soil.py

### ISSUE THREAD

**Issue by TomasMiskov** [aquacropos/aquacrop#83]
Getting the following `FutureWarning`:
```
C:\Users\...\miniconda3\lib\site-packages\aquacrop\entities\soil.py:333: FutureWarning: 
In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array.
To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
```

Seems like it concerns lines 321-338 and 348-350 in soil.py
Will have a look if I can fix it, seems like a simple patch.

**Comment by Bowhaven** [comment]
Thanks for raising this. The lines you mention appear to now follow the recommended syntax in the FutureWarning and there is no longer a warning so will close this issue.
