### ISSUE TITLE
Change irrigation mode

### ISSUE THREAD

**Issue by pzw28** [aquacropos/aquacrop#87]
Dear teachers：
         When I try to use  Predefined irrigation schedule (IrrMethod=3)  and Input different  schedules，but  running IrrigationManagement(irrigation_method=3,schedule=schedule)，the schedule all will  become empty,and then runing the model core  the schedule all will  become zero，in model._outputs  ，the Seasonal irrigation all is zero. I hope teachers can help me solve this problem。

**Comment by Bowhaven** [comment]
Hello, we would like to help you with your problem, but we require a bit more information. Could you please provide a reproducible example of what you are trying to do? For example, showing us what your different/custom irrigation schedules look like would be very helpful.

**Comment by buwenliu** [comment]
![image](https://github.com/aquacropos/aquacrop/assets/62497381/a09d7483-e40d-4888-92b2-522fc3263046)
When method=3, the schedule method and rainfall method have the same result, which obviously should not be the case. What should the teacher do to solve the problem?

**Comment by pzw28** [comment]
If you use aquacropos, check the irrigation documents (.txt). If you use aquacrop-ospy, check that the code is consistent with the built-in code (spelling of letters, capitalisation of first letters).

| |
PZW
|
|
***@***.***
|
---- Replied Message ----
| From | ***@***.***> |
| Date | 3/28/2024 00:16 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [aquacropos/aquacrop] Change irrigation mode (Issue #87) |

image.png (view on web)
When method=3, the schedule method and rainfall method have the same result, which obviously should not be the case. What should the teacher do to solve the problem?

**Comment by buwenliu** [comment]
Thank you!Ihava find it.( capitalisation of first letters) @pzw28 🙂
